name: "SQDLib"
version: "${version}"
main: net.chamosmp.sqdlib.paper.plugin.SqdlibPlugin
api-version: "1.21"

folia-supported: true

website: "https://github.com/SQD-Studios/sqd-lib"
authors: ["SQD Studios"]

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true